### ISSUE TITLE
PRACTICA DE HILOS

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/practica-de-hilos-Valentiin01#2]
[PRACTICA HILOS_GENARO SANTIAGO VALENTIN.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Valentiin01/files/6769941/PRACTICA.HILOS_GENARO.SANTIAGO.VALENTIN.pdf)

**Comment by Eva155** [comment]
EL TRABAJO CUMLE CON TODO LOS REQUERIMIENTOS 
CALIFICACIÓN: 20 PUNTOS
CALIFICÓ: EVA AGUILAR AVENDAÑO

**Comment by josealfredo79** [comment]
esta bien hecho y revisado...solo que se entrego al final del semestre
